# tasks file for hdp-instances
---
- block:
   - name: launch utility
     ec2:
       image: "{{ image }}"
       region: "{{ region }}"
       instance_type: "{{ utility_instance_type }}"
       key_name: "{{ key_name }}"
       group: "{{ security_group }}"
       instance_tags: { Name: hdp-utility, type: utility, env: test, purpose: hdp }
       wait: false
       volumes:
         - device_name: /dev/sda1
           volume_type: gp2
           volume_size: 100
           delete_on_termination: true
           #         - device_name: /dev/sdb
           #           ephemeral: ephemeral0
           #           delete_on_termination: true
       vpc_subnet_id: subnet-3cfe6d59
       assign_public_ip: yes
       exact_count: 1
       count_tag: {type: utility}
     register: utility_node

   - name: add new utility instance to host group
     add_host:
       hostname: "{{ item.public_dns_name }}"
       groupname:
         - utility
         - hdp
     with_items: "{{ utility_node.instances }}"

   - name: launch master1
     ec2:
       image: "{{ image }}"
       region: "{{ region }}"
       instance_type: "{{ master1_instance_type }}"
       key_name: "{{ key_name }}"
       group: "{{ security_group }}"
       instance_tags: { Name: hdp-master1, type: master1, env: test, purpose: hdp }
       wait: false
       volumes:
         - device_name: /dev/sda1
           volume_type: gp2
           volume_size: 100
           delete_on_termination: true
           #         - device_name: /dev/sdb
           #           ephemeral: ephemeral0
           #           delete_on_termination: true
       vpc_subnet_id: subnet-3cfe6d59
       assign_public_ip: yes
       exact_count: 1
       count_tag: {type: master1}
     register: master1_node

   - name: add new master1 instance to host group
     add_host:
       hostname: "{{ item.public_dns_name }}"
       groupname:
         - master1
         - hdp
     with_items: "{{ master1_node.instances }}"


   - name: launch worker
     ec2:
       image: "{{ image }}"
       region: "{{ region }}"
       instance_type: "{{ worker_instance_type }}"
       key_name: "{{ key_name }}"
       group: "{{ security_group }}"
       instance_tags: { Name: hdp-worker, type: worker, env: test, purpose: hdp }
       wait: false
       volumes:
         - device_name: /dev/sda1
           volume_type: gp2
           volume_size: 100
           delete_on_termination: true
           #         - device_name: /dev/sdb
           #           ephemeral: ephemeral0
           #           delete_on_termination: true
       vpc_subnet_id: subnet-3cfe6d59
       assign_public_ip: yes
       exact_count: "{{ worker_count }}"
       count_tag: {type: worker}
     register: worker_node

   - name: add new worker instance to host group
     add_host:
       hostname: "{{ item.public_dns_name }}"
       groupname:
         - worker
         - hdp
     with_items: "{{ worker_node.instances }}"
     when: "{{ worker_node.instances }}"

   - name: wait for SSH to come up
     wait_for: host={{ item }} port=22 delay=2 timeout=200 state=started
     with_items: "{{ groups.hdp }}"

   - name: wait 2 more seconds
     pause: prompt=no seconds=2

  tags:
    - ec2_setup
